name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: chanuthdk
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: chanuthdk
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          theme: dark
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update snake animation"
          git push
